version: "3.8"
services:
  app:
    container_name: hfms
#    build: .
    image: "ghcr.io/ben-mathu/homefinancemanagerapi:develop"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hfms
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_test
    hostname: localhost
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=licenseAndStickers