name: HFMS Publish Docker Image

on:
  push:
    branches: [ "master", "develop" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  # GitHub repository as <account/repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Used to complete the identity challenge
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Project
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Grant Permissions
        run: chmod +x mvnw

      - name: Create Package
        run: ./mvnw clean compile

      # install cosign tool to verify installations.
      # Verifies the integrity of the cosign release during installation.
      # https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Cosign Version
        run: cosign version

      # used to build and push any image
      # https://github.com/docker/build-push-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Login to Registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata {tags, labels} fpr docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker Metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push image
      # https://github.com/docker/build-push-action
      - name: Build/Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      # Sign Docker Image Digest
      # https://github.com/sigstore/cosign
      - name: Sign Docker Image
        env:
          CONSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
